Added Travis CI
CraftAcademy/evensteven pull request #5
Opened 2018-02-26 19:03 UTC by jyuw

#### PT Story: https://www.pivotaltracker.com/story/show/155514254
#### Description
Changes proposed in this pull request:

* Added the travis yaml file

#### What I have learned working on this feature: 
How to add Travis

2018-02-26 19:31 UTC, diraulo requested changes
👎

2018-02-26 19:31 UTC, diraulo commented on .travis.yml
> +  - bundle install
You don't need to do `bundle install` Travis will do that automatically for every ruby projects

2018-02-26 19:31 UTC, diraulo commented on .travis.yml
> +  - bundle exec rake db:create --all
Move all DB Setup in a `before_script:` block.
Also you don't need the `--all` of creating the DB and you can compact this in one line

`bundle exec rails db:create db:test:prepare` should do the trick in principle

2018-02-26 19:31 UTC, diraulo commented on .travis.yml
> +install:
Doesn't make any difference to Travis but IMO it makes sense to order these in the order in which they're actually executed.

So I'd move this step above before the `script` and `before_script`

2018-02-26 20:19 UTC, diraulo requested changes
Minor changes and I think we can get this in if it actually passes on Travis. I just enabled Travis for this repo so the next commit you push should trigger a build.

2018-02-26 20:19 UTC, diraulo commented on .travis.yml
> +  - bundle exec rake
This line actually executes the test and should be in the `script`  block

2018-02-26 20:19 UTC, diraulo commented on .travis.yml
> +services:
Move this before the `install` block

2018-02-26 20:31 UTC, diraulo commented
You should merge the `master` branch onto this one to have it in sync - I see the logs are back on branch. Once that's done we can merge this in.

2018-02-27 05:56 UTC, diraulo requested changes
Please remove the log files

2018-02-27 07:20 UTC, tochman commented on .travis.yml
> +  - wget -N http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P ~/
I don’t understand. Why are you installing Chrome on Travis? You are not using Chromedriver in your tests.

2018-02-27 08:24 UTC, diraulo requested changes
I was about to approve this PR as agreed in Scrum.. but now I'm gonna have to reject it. This Feature is only about setting up Travis. You should deal with coveralls on a separate PR

2018-02-27 08:27 UTC, diraulo commented
@jyuw Okay, I see you've added Coveralls to the story on PT. You should probably change the title of this PR to reflect what you're doing. eg `Setup continuous integration and coverage report`

As for Coveralls you're only setting it up for RSpec. What about Cucumber? And also you should probably merge both reports

2018-02-27 08:28 UTC, jyuw commented
The Pivotal Tracker story has both Travis and Coveralls in it, is that not allowed?

2018-02-27 08:49 UTC, diraulo commented
You forgot to exclude the `coverage` folder from version control 🤔

2018-02-27 08:54 UTC, diraulo approved these changes
👍

2018-02-27 08:54 UTC, merged